[tool.pytest.ini_options]
addopts = "--color=yes"
testpaths = [
    "tests",
]

[tool.isort]
# make it compatible with black
profile = "black"


[tool.black]
line-length = 120 # override black's default line-length
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | venv
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
